[package]
name = "downloader"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["io"] }
reqwest = { version = "0.11", features = ["json","stream", "rustls-tls"] }
webpki-roots = "0.22.1"
hyper-rustls = "0.22.1"
futures = "0.3"
futures-util = "0.3"
futures-core = "0.3"
flate2 = "1.0"
async-compression = { version = "0.3", features = ["stream", "tokio", "gzip"] }
bytes = {version = "1.0", features = ["std"]}
async-std = "1.10"
tokio-tar = { path = "../tokio-tar" }
derivative = "2.0"
nix = "0.23.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["serde_derive", "rc"] }
serde_json = "1.0"
serde_with = { version="1.6", features = [ "macros" ] }
libc = "0.2"
sha2 = { version = "0.9.1" }
rand = "0.8"
uuid = { version = "0.8.2", features = ["v4"] }
nydus-bootstrap = { path = '../bootstrap'}
glob = "0.3.0"
async-recursion = "1.0.0"
async-trait = "0.1.52"
log = "0.4.16"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-5", "channel-api"]
