timeout: 120000
spec:
  - integration/test/normal/**/*.test.js
ignore:
  - integration/test/normal/fixtures/**
recursive: true
extension:
  - js
require:
  - intelli-espower-loader
full-trace: true
exit: true
