[package]
name = "tnpm-rs-binding"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0.3"
downloader = { path = "../downloader" }
serde = { version = "1.0", features = ["serde_derive", "rc"] }
serde_json = "1.0"
nydus-bootstrap = { path = '../bootstrap' }
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.0.3", default-features = false, features = ["napi5", "async", "compat-mode"] }
napi-derive = { version = "2.0.7", features = ["compat-mode"] }
simple_logger = "2.1.0"
ctor = "0.1.22"
log = "0.4.16"

[build-dependencies]
napi-build = "1.2.1"
