[package]
name = "nydus-utils"
version = "0.1.0"
authors = ["The Nydus Developers"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
built = { version = "=0.4.3", features = ["git2", "chrono"] }

[dependencies]
log = "0.4.8"
flexi_logger = { version = "0.17"}
libc = "0.2"
nix = "0.17"
serde = { version = ">=1.0.27", features = ["serde_derive", "rc"] }
serde_json = ">=1.0.9"
backtrace = "0.3"
chrono = "0.4.19"
num-traits = "0.2.14"
